# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Looi Kai Wen
email: kaiwen98@gmail.com
author:
  name: Looi Kai Wen
  about: I am a Year 4 Computer Engineering Student in NUS! I like good, clean and scalable code, and am interested in systems design and web development. I am also a tinker at heart, and am deeply interested in the Internet Of Things field!

description: "I am Looi Kai Wen, a Year 4 Computer Engineering Student in NUS! \nI like good, clean and scalable code, and am interested in systems design and web development. \nI am also a tinker at heart, and am deeply interested in the Internet Of Things field!\n"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


contacts:
  - title: twitter 
    url: 'https://twitter.com/okai_iwen'
  - title: github
    url:  'https://github.com/kaiwen98'
  # - title: facebook
  #   url: 'https://example.com/@jekyllrb'
  - title: instagram
    url: 'https://instagram.com/okai_iwen'
  - title: linkedin
    url: 'https://example.com/@jekyllrb'
  # - title: youtube
  #   url: 'https://example.com/@jekyllrb'
  # - title: twitch
  #   url: 'https://example.com/@jekyllrb'
  # - title: telegram
  #   url: 'https://example.com/@jekyllrb'
  # - title: whatsapp
  #   url: 'https://example.com/@jekyllrb'
  # - title: discord
  #   url: 'https://example.com/@jekyllrb'
  # - title: slack
  #   url: 'https://example.com/@jekyllrb'
  - title: email
    url: mailto:kaiwen98@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
